// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DeleteFTPConfig(arg1) {
  return window['go']['main']['App']['DeleteFTPConfig'](arg1);
}

export function DownloadLog(arg1, arg2) {
  return window['go']['main']['App']['DownloadLog'](arg1, arg2);
}

export function FetchLocalLog(arg1, arg2) {
  return window['go']['main']['App']['FetchLocalLog'](arg1, arg2);
}

export function GetFTPConfig(arg1) {
  return window['go']['main']['App']['GetFTPConfig'](arg1);
}

export function GetFileInfos(arg1) {
  return window['go']['main']['App']['GetFileInfos'](arg1);
}

export function GetLocalFileInfos(arg1) {
  return window['go']['main']['App']['GetLocalFileInfos'](arg1);
}

export function ListFTPConfigs() {
  return window['go']['main']['App']['ListFTPConfigs']();
}

export function LogError(arg1) {
  return window['go']['main']['App']['LogError'](arg1);
}

export function LogInfo(arg1) {
  return window['go']['main']['App']['LogInfo'](arg1);
}

export function LogWarning(arg1) {
  return window['go']['main']['App']['LogWarning'](arg1);
}

export function SaveFTPConfig(arg1) {
  return window['go']['main']['App']['SaveFTPConfig'](arg1);
}
