// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function DeleteFTPConfig(arg1:string):Promise<void>;

export function DownloadLogs(arg1:main.FTPConfig):Promise<void>;

export function GetFTPConfig(arg1:string):Promise<main.FTPConfig>;

export function GetFileInfos(arg1:main.FTPConfig):Promise<main.SiteInfo>;

export function ListFTPConfigs():Promise<Array<string>>;

export function SaveFTPConfig(arg1:main.FTPConfig):Promise<void>;
