// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetFTPConfig(arg1) {
  return window['go']['main']['App']['GetFTPConfig'](arg1);
}

export function SaveFTPConfig(arg1) {
  return window['go']['main']['App']['SaveFTPConfig'](arg1);
}
