// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DeleteFTPConfig(arg1) {
  return window['go']['main']['App']['DeleteFTPConfig'](arg1);
}

export function DownloadLogs(arg1) {
  return window['go']['main']['App']['DownloadLogs'](arg1);
}

export function GetFTPConfig(arg1) {
  return window['go']['main']['App']['GetFTPConfig'](arg1);
}

export function GetFileInfos(arg1) {
  return window['go']['main']['App']['GetFileInfos'](arg1);
}

export function ListFTPConfigs() {
  return window['go']['main']['App']['ListFTPConfigs']();
}

export function SaveFTPConfig(arg1) {
  return window['go']['main']['App']['SaveFTPConfig'](arg1);
}
